# -*- coding: utf-8 -*-
"""Final_LSTM_SDv4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rslAhMOC0byR7XzBn-w_avT0--8j8d7c
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import make_scorer, mean_squared_error
from sklearn.base import BaseEstimator, RegressorMixin
from statsmodels.tsa.seasonal import seasonal_decompose
import statistics
import math
import time

def prepare_data(data, sequence_length=12, train_test_split=.75):
    # data is a list
    data_normalized = scaler.fit_transform(np.array(data).reshape(-1, 1)).flatten()

    # sequence_length=12 means use past 12 hours of data to predict the next hour
    # data_X is a list of subsequences of length sequence_length.
    # data_y has the real target value that comes immedietly after the corresponding subsequence in data_X
    # LSTM model is trying to predict the ith value of data_y based on the ith subsequence in data_X
    # doing this is what allows the model to find patterns in the data
    data_X, data_y = [], []
    for i in range(len(data_normalized) - sequence_length):
        data_X.append(data_normalized[i:i+sequence_length])
        data_y.append(data_normalized[i+sequence_length])


    # convert python lists to numpy ndarrays
    data_X = np.array(data_X)
    data_y = np.array(data_y)

    # convert ndarrays to tensors, needed for pytorch
    X = torch.tensor(data_X, dtype=torch.float32)
    y = torch.tensor(data_y, dtype=torch.float32)

    # split data into train and test
    split = math.floor(len(X) * train_test_split)
    X_train, X_test = X[:split], X[split:]
    y_train, y_test = y[:split], y[split:]

    # reshape data for LSTM model
    X_train = X_train.view(-1, sequence_length, 1)
    X_test = X_test.view(-1, sequence_length, 1)

    # prepare output
    train_loader = (X_train, y_train)
    test_loader = (X_test, y_test)
    return train_loader, test_loader, split, sequence_length

# Define LSTM Model

class LSTMModel(nn.Module):
    def __init__(self, input_size=1, hidden_layer_size=50, output_size=1):
        super().__init__()
        self.hidden_layer_size = hidden_layer_size  # I found the optimal hidden layer size to be 50 (tested 50, 75, 100)
        # defining the different layers of the LSTM model
        self.lstm = nn.LSTM(input_size, hidden_layer_size)
        self.linear = nn.Linear(hidden_layer_size, output_size)
        self.hidden_cell = (torch.zeros(1,1,self.hidden_layer_size),
                            torch.zeros(1,1,self.hidden_layer_size))

    def forward(self, input_seq):
        # specifies how each pass through the model works
        # Pytorch does this for me when the model is training, which is why it is never called explicitly in the code.
        lstm_out, self.hidden_cell = self.lstm(input_seq.view(len(input_seq) ,1, -1), self.hidden_cell)
        predictions = self.linear(lstm_out.view(len(input_seq), -1))
        return predictions[-1]

def Training(model, optimizer, train_loader, num_epochs=20):
    start = time.time()
    loss_function = nn.MSELoss()
    # MSE loss makes the most sense imo

    for i in range(num_epochs):
        for seq, labels in zip(train_loader[0], train_loader[1]):
            optimizer.zero_grad()         # reset gradient from pervious iterations

            # reset hidden layer
            model.hidden_cell = (torch.zeros(1, 1, model.hidden_layer_size),
                            torch.zeros(1, 1, model.hidden_layer_size))

            y_pred = model(seq)           # performs prediction on seq using the model
            single_loss = loss_function(y_pred, labels)     # calculate mse
            single_loss.backward()        # backpropogation
            optimizer.step()              # update optimizer weights

        if i%3 == 0:
            print("epoch: {:3} loss: {:10.8f} time elapsed: {}".format(
                i, single_loss.item(), time.time()-start))

    return model

def Testing(model, test_loader, split, sequence_length, timestamps, name, future=48):
    model.eval()
    y_pred = []
    for seq in test_loader[0]:  # Iter over the test loader
        with torch.no_grad():
            # reset the hidden layer for each seq, then append predicted value to y_pred
            model.hidden = (torch.zeros(1, 1, model.hidden_layer_size),
                            torch.zeros(1, 1, model.hidden_layer_size))
            y_pred.append(model(seq).item())


    # transform y_pred to be similar to y_test
    y_pred_trans = scaler.inverse_transform(np.array(y_pred).reshape(-1, 1)).flatten()
    y_test = test_loader[1]


    # calculate and return the RMSE value, then plot the predicted and real values for the testing data
    mse = mean_squared_error(scaler.inverse_transform(y_test.reshape(-1, 1)), y_pred_trans)
    rmse = np.sqrt(mse)
    print("RMSE: ", rmse)

    plt.figure(figsize=(15, 6))
    plt.plot(timestamps[split+sequence_length:], y_pred_trans, label='Predicted')
    plt.plot(timestamps[split+sequence_length:], scaler.inverse_transform(y_test.reshape(-1, 1)).flatten(), label='Real')
    plt.xlabel('Timestamp')
    plt.ylabel('CPU Usage')
    plt.title('Real vs Predicted CPU Usage')
    plt.legend()
    plt.savefig(name)
    plt.show()

    return rmse, y_pred

df = pd.read_csv('by_half_hour.csv',  parse_dates=True)
timestamp_list = df["Timestamp"].tolist()
timestamps = pd.to_datetime(timestamp_list)
cpu_data = df["Avg_CPU_95"].tolist()

# MinMaxScaler scales the data so that it is all within the range of (0,1)
scaler = MinMaxScaler(feature_range=(0, 1))

train, test, split, sequence_length = prepare_data(cpu_data, sequence_length=12, train_test_split=.75)
model = LSTMModel(hidden_layer_size=50)
optimizer = torch.optim.Adam(model.parameters(), lr=.0001)

result = Training(model, optimizer, train, num_epochs=25)
rmse, Y_Pred = Testing(result, test, split, sequence_length, timestamps, "Real_Pred_Graph")
print("rmse: ", rmse)

print("Range of Data:  " , max(cpu_data)-min(cpu_data))

"""# Testing on Other Data"""

# The new dataset we received from Lockheed
df2 = pd.read_csv('LSTM_by_time_period.csv',  parse_dates=True)
timestamps2_list = df2["Timestamp"].tolist()
timestamps2 = pd.to_datetime(timestamps2_list)
cpu_data2 = df2["Avg_CPU_95"].tolist()

# we dont want to train the model again on this data, just test on it, hence the split=0
# if split=0, train2 is empty
train2, test2, split2, seq_len2 = prepare_data(cpu_data2, train_test_split=0)

rmse2, y_pred2 = Testing(result, test2, split2, seq_len2, timestamps2, "Jan-Feb_Graph")

print(max(cpu_data2)-min(cpu_data2))

"""# Custom Time Window"""

def time_window_testing(model, test_loader, timestamps, split=0, sequence_length=0, name="Limited_Time_Graph"):
    #
    # if user wants to only view a subset of the testing results, use this function
    # split and sequence_length should be 0 if not using the train dataset
    # if using the train dataset, they should be their real values.

    timestamps = timestamps[0+split+sequence_length:]


    print("earliest timestamp: ", timestamps[0])
    print("latest timestamp: ", timestamps[-1])
    start_time = input("select start time to view (YYYY-MM-DD HH:SS:00):  ")
    end_time = input("select end time to view (YYYY-MM-DD HH:SS:00):  " )


    try:
        start_time = pd.to_datetime(start_time)
    except ValueError:
        start_time = pd.to_datetime(timestamps[0])

    try:
        end_time = pd.to_datetime(end_time)
    except ValueError:
        end_time = pd.to_datetime(timestamps[-1])


    if start_time < timestamps[0]:
        start_time=timestamps[0]
    if end_time > timestamps[-1]:
        end_time=timestamps[-1]

    start_timestamp_index = timestamps.get_loc(start_time)
    end_timestamp_index = timestamps.get_loc(end_time)


    # rest is copied from Testing()
    model.eval()
    y_pred = []
    for seq in test_loader[0]:  # Iter over the test loader
        with torch.no_grad():
            # reset the hidden layer for each seq, then append predicted value to y_pred
            model.hidden = (torch.zeros(1, 1, model.hidden_layer_size),
                            torch.zeros(1, 1, model.hidden_layer_size))
            y_pred.append(model(seq).item())

    # transform y_pred to be similar to y_test
    y_pred_trans = scaler.inverse_transform(np.array(y_pred).reshape(-1, 1)).flatten()
    y_test = test_loader[1]

    print("len y_pred: ", len(y_pred_trans))
    print("len y_test: ",len(y_test))
    print("len timestamps: ",len(timestamps))
    print()
    print("len y_pred: ", len(y_pred_trans[start_timestamp_index:end_timestamp_index]))
    print("len timestamps: ", len(timestamps[start_timestamp_index:end_timestamp_index+1]))



    # timestamps[0+split+sequence_length+start_timestamp_index] corresponds to y_pred_trans[0]

    # calculate and return the RMSE value, then plot the predicted and real values for the testing data
    mse = mean_squared_error(scaler.inverse_transform(y_test.reshape(-1, 1)), y_pred_trans)
    rmse = np.sqrt(mse)
    print("RMSE: ", rmse)

    plt.figure(figsize=(15, 6))
    plt.plot(timestamps[start_timestamp_index:end_timestamp_index], y_pred_trans[start_timestamp_index:end_timestamp_index], label='Predicted')
    plt.plot(timestamps[start_timestamp_index:end_timestamp_index], scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()[start_timestamp_index:end_timestamp_index], label='Real')
    plt.xlabel('Timestamp')
    plt.ylabel('CPU Usage')
    plt.title('Real vs Predicted CPU Usage')
    plt.legend()
    plt.savefig(name)
    plt.show()

    return rmse, y_pred

fil, ler = time_window_testing(result, test2, timestamps2, split2, seq_len2)

abra, cadabra = time_window_testing(result, test, timestamps, split, sequence_length)

"""# Scheduling"""

def scheduling(timestamps, y_pred, periods=48):

    last_24h_time = timestamps[-periods:]
    last_24h_pred = y_pred[-periods:]
    median_cpu = statistics.median(last_24h_pred)

    #print(last_24h_time)
    #print(last_24h_pred)
    #print(median_cpu)
    #print()

    on_off_df = pd.DataFrame(last_24h_time, columns=['Time'])
    on_off_df['Servers'] = False

    for index, row in on_off_df.iterrows():
        if last_24h_pred[index] > median_cpu:
            on_off_df.at[index, 'Servers'] = True

    return on_off_df

schedule = scheduling(timestamps, Y_Pred)
print(schedule)

"""# Seasonality"""

# Basic method of seeing trend and seasonality of data. period=48 because there are
# 48 observations per period, period being each day and there being 48 half-hour intervals each day
seasonal_res = seasonal_decompose(df['Avg_CPU_95'], period=48)
seasonal_res.plot()